Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables. 

- Ans: Yes, there is a difference in the data type of the list_ and array_list variables. The list_ is a Python list containing strings, while array_list is a NumPy array with dtype determined by the data type of the elements in the list.

In [2]:
import numpy as np

In [3]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

In [4]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [5]:
list_

['1', '2', '3', '4', '5']

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [6]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [7]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Print data types of elements in num_list
print("\nData types of elements in num_list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

# Print data types of elements in num_array
print("\nData types of elements in num_array:")
for element in num_array.flatten():
    print(type(element))


Data types of elements in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in num_array:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [8]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape_of_num_array = num_array.shape
print("(i) Shape of num_array:", shape_of_num_array)

# (ii) Find the size of num_array
size_of_num_array = num_array.size
print("(ii) Size of num_array:", size_of_num_array)

(i) Shape of num_array: (2, 3)
(ii) Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [9]:
# Create a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

# Print the created matrix
print("3x3 Matrix containing zeros:")
print(zero_matrix)

3x3 Matrix containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [10]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the created identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
